### PR TITLE
Bump kotlin version to 1.6.0

### PR DESCRIPTION
**Pull request by khorark**
Bump Kotlin version to 1.6.0 for fix build android version for react native >0.70.x

### CODE REVIEW

**Comment by micahlt** [comment]
@osamaqarem could we please get this merged?  Would help a ton with compatibility with RN 0.71.2!

**Comment by osamaqarem** [comment]
> @osamaqarem could we please get this merged?  Would help a ton with compatibility with RN 0.71.2!  I've tested it and it works perfectly fine with this PR.

Oh sorry I missed this PR. Will take a look soon.

**Comment by osamaqarem** [comment]
Thanks for the PR - merging and releasing 👍

FYI if this issue happens again in the future you can define a variable `kotlinVersion` in your `android/build.gradle` 

```
kotlinVersion = "1.6.0"
```
 
this package checks for this here:

https://github.com/osamaqarem/react-native-image-colors/blob/4ad55ca1fadd4a988aef65e35295a6b1b4ba8de7/android/build.gradle#L3

**Comment by micahlt** [comment]
Ah, excellent! Thank you so much!

**Pull request merged**
