### PR TITLE
android: fix build with rn 0.73

### PR DESCRIPTION
**Pull request by kesha-antonov**
Hi

PR fixes error
```
Execution failed for task ':react-native-image-colors:compileDebugKotlin'.
> 'compileDebugJavaWithJavac' task (current target is 17) and 'compileDebugKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version. Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain * 
```

### CODE REVIEW

**Comment by osamaqarem** [comment]
hey, thanks for your contribution!

While the fix is valid, I hope to maintain the same changes as done by the official template this project is based on (expo-module-template): 

1. https://github.com/expo/expo/commit/7ec55dfae4942ced223d1a67950e92ebf8f6c7e3
image

2. https://github.com/expo/expo/commit/c8003cb9cec4693e13816550a93a0c4bc41f6e15
image

**Comment by kesha-antonov** [comment]
> hey, thanks for your contribution!
> 
> While the fix is valid, I hope to maintain the same changes as done by the official template this project is based on (expo-module-template):
> 
> 1. [expo/expo@7ec55df](https://github.com/expo/expo/commit/7ec55dfae4942ced223d1a67950e92ebf8f6c7e3)
>    image
> 2. [expo/expo@c8003cb](https://github.com/expo/expo/commit/c8003cb9cec4693e13816550a93a0c4bc41f6e15)
>    image

Thanks for the reference, I'll change PR

**Comment by osamaqarem** [comment]
Heya! do you still plan on working on this? I'd like to get a fix out soon so I'll probably work on this tomorrow unless you still want to.

**Comment by osamaqarem** [comment]
Closing in favor of https://github.com/osamaqarem/react-native-image-colors/pull/85

**Pull request closed without merging**
