### PR TITLE
fix(agp): do not apply namespace if its not available

### PR DESCRIPTION
**Pull request by osamaqarem**
Based on https://github.com/software-mansion/react-native-gesture-handler/pull/2448

### CODE REVIEW

**Comment by KrzysztofMoch** [comment]
Also should we try implement [this solution](https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1600015842) ? Example [here](https://github.com/react-native-cameraroll/react-native-cameraroll/pull/505)

**Comment by osamaqarem** [comment]
yeah we should add it back, thanks for catching that. but i'm not sure about conditionally taking it out too via code - it might be ignored https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1606270442 but I need to test it.

**Comment by atlj** [comment]
@osamaqarem Please see the following comment as well: https://github.com/react-native-community/discussions-and-proposals/issues/671#issuecomment-1607191009

**Comment by KrzysztofMoch** [comment]
@osamaqarem can i complete this PR or you have already changes on local ?

**Comment by osamaqarem** [comment]
I'm thinking to close this PR as integration of expo-modules-core requires AGP 7 minimum, which means if you're on RN67 (AGP 4) you had to upgrade your AGP to 7 to use expo-modules-core in the first place.

In other words, if we were never compatible with AGP 4 (RN67 and below) then we never broke backward compatibility.

I couldn't find docs that say this, but there is this comment on a related issue
https://github.com/expo/expo/issues/17862#issuecomment-1159632073

And then implicitly by expo-modules-core manual integration steps (setting AGP to 7.4):
https://docs.expo.dev/bare/installing-expo-modules/

Lastly, there is guide on from expo about changes needed for custom expo modules about those Gradle/AGP changes, and they don't address the concern of backward compatibility.
https://github.com/expo/fyi/blob/main/expo-modules-gradle8-migration.md

**Comment by KrzysztofMoch** [comment]
Okay, sounds reasonable

**Pull request closed without merging**
